// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmaaeltbacyluzerdjpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtYWFlbHRiYWN5bHV6ZXJkanB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTk0MTksImV4cCI6MjA2Njk5NTQxOX0.AGHRJwQxiyJLZSGLMChNn_j6N2xFKULKy8oYFtIYYlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});